# Generated by Django 4.2.10 on 2026-03-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_absence_id_alter_classlog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlog',
            name='assignments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
