# Generated by Django 4.2.10 on 2026-03-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Absence',
        ),
    ]
